name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    env:
      Version: ""
    steps:
      - name: Connect to Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ github.token }}
      - name: Update tag version
        run: |
          major=$(git tag | tail -1 | awk -F \. {'print $1'})
          minor=$(git tag | tail -1 | awk -F \. {'print $2'})
          patch=$(git tag | tail -1 | awk -F \. {'print $3'})

          patch=$((patch + 1))
          newTag="${major}.${minor}.${patch}"
          echo $newTag
          git tag $newTag
          git push --tags
      
      - name: 'Docker Stage'
        run: |
          docker build -t hwapp .
          docker run hwapp -v ./Artifact/:/App/
          cat /Artifact/hello.txt
