name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    env:
      Version: ""
    steps:
      - name: Connect to Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ github.token }}
      - name: Update tag version
        run: |
          echo $(git describe --tags $(git rev-list --tags --max-count=1))
          major=$(git tag | tail -1 | awk -F \. {'print $1'})
          minor=$(git tag | tail -1 | awk -F \. {'print $2'})
          patch=$(git tag | tail -1 | awk -F \. {'print $3'})

          echo patch
          echo $patch
          patch=$((patch + 1))
          echo patch
          echo $patch
          newTag="${major}.${minor}.${patch}"
          echo $newTag
          git tag $newTag
          git push --tags
      
      - name: 'Docker Stage'
        run: |
          docker build -t hwapp .
          docker run -d hwapp
          docker ps
          # dockerProcessID=docker ps | grep hwapp | awk '{ print $1 }'
          # docker cp ${dockerProcessID}:/App/hello.txt ./Artifact
