name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    env:
      Version: ""
    steps:
      - name: Get last tag
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ github.token }}
      - name: 2nd stage
        run: |
          tag=$(git describe --tags `git rev-list --tags --max-count=1` |  awk -F \. {'print $3'})
          echo $tag
      # - name: Create tag
      #   uses: actions/github-script@v5
      #   with:
      #     script: |
      #       github.rest.git.createRef({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         ref: 'refs/tags/<tagname>',
      #         sha: context.sha
      #       })